### ISSUE TITLE
Sorting needed on course page

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#1]
We'd like to be able to sort by the columns to allow us to sort by last name for example among registered users for a given course.

**Comment by cameroneickmeyer** [comment]
This is also important to allow our admins on officials courses to sort alphabetically before printing and produce the sheets or exams in alphabetical order. Would be a very nice to have.

**Comment by sn-np** [comment]
What are they printing? The screen? 

If you want the labels to print alphabetically, that is completely separate from how things appear on screen.

**Comment by cameroneickmeyer** [comment]
ah, ok, well then it's separate. They want to be able to sort these fields but then also print labels/exams alphabetically by default

**Comment by sn-np** [comment]
Added sort on screen (and barcodes are alphabetical now too).
