### ISSUE TITLE
v1.x: Double email address entry

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#13]
Would like to help eliminate email address typos by requiring users upon account creation to enter their email twice. Ideally not allow them to copy and paste from one field to another.

**Comment by cameroneickmeyer** [comment]
This would be a very nice to have if possible. I've helped probably 5 people since Tuesday with email address typos.

**Comment by sn-np** [comment]
This is in place.
