### ISSUE TITLE
Assigning instructors problem

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#14]
We have courses in New York (Course ID 224) that is having trouble with giving two instructors assignments to the course. They want Nicholas Tochelli and Gary Cutler assigned but attempting to add more than one is booting one off and allowing only one person. Any idea why?

**Comment by sn-np** [comment]
This is a bug, introduced when we added the pagination on to that screen (essentially, the different "pages" aren't talking to each other like they should). I'll work on fixing it, but this one will take a little bit for me to sort through the best way to solve. Meantime, I have manually added both instructors to the course.

**Comment by sn-np** [comment]
This should be fixed. You'll need a refresh to get the fix.

**Comment by cameroneickmeyer** [comment]
After saving an update to add a new instructor the list of assigned instructors disappears and can only be seen again by signing out and back in. If you did NOT sign out/back in and went back into "update" the instructors the search function no longer works.

**Comment by sn-np** [comment]
I'm having trouble duplicating this one. Can you further explain: what permissions does the user who experiences this issue have? What operating system? Are there any other steps needed?

**Comment by cameroneickmeyer** [comment]
These are instructors in the New York area trying to assign each other. I will try to get more details on OS etc.

**Comment by cameroneickmeyer** [comment]
"Internet Explorer. It was on the Newburgh (New York) level one I know it happened. It also happened to Gary Cutler (instructor). 

When I used my iPad, I had the same problem. " - Andrea Balga NY District Admin Officiating

**Comment by sn-np** [comment]
Addressed. Andrea out of NY verified fix worked on their end.
