### ISSUE TITLE
Confirmation number problem

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#15]
We have another user with a confirmation number that is valid but doesn't show up in the search. Can you see what's happening?
![screen shot 2017-07-14 at 10 59 10 am](https://user-images.githubusercontent.com/27363244/28222231-d36cdf7e-6883-11e7-8218-f8a2600b809f.png)

**Comment by sn-np** [comment]
I don't think I understand this one. The 16/17 number was obviously recognized cause he was able to create an account. Is it a 17/18 number that isn't recognized? In which case, what is the error that the user sees when they attempt to add it to their account?

**Comment by cameroneickmeyer** [comment]
The 17/18 number is in that screenshot 16380047COXCH and when he tries to enter that to update his membership he's told it's in use by another user.

**Comment by sn-np** [comment]
Both the 16/17 and 17/18 numbers are already associated with this user. But it looks like he added the 16/17 number AFTER the 17/18 number.

But the two numbers are associated with different USAH membership id #s, and the 17/18 membership is for a level 0 coach, while the 16/17 was for a level 1 coach. It seems like maybe you need to merge some records on your end first? And then let me know which confirmation number to keep or clear out.

**Comment by sn-np** [comment]
I just realized part of the confusion here -- I hadn't realized you were searching based on the 17/18 # and then seeing results with another number.

So: the fundamental issue is that while the system keeps old confirmation numbers for records/lookup purposes, only the most recently entered confirmation number is used to determine eligibility for a course registration.  Do you expect a lot of users to enter new numbers, followed by old numbers?

**Comment by cameroneickmeyer** [comment]
I don’t think they’d enter old numbers very often so I think these would be outliers.

**Comment by sn-np** [comment]
OK. So here is what I propose:
I will remove the 16/17 number from the system, so the 17/18 number is what is viewed. This user will need to do a refresh of their credentials, AFTER you (or Alison?) has linked his two member_ids in Ralph's system so that his credentials are correct. That work?

**Comment by cameroneickmeyer** [comment]
yes. please

**Comment by sn-np** [comment]
all set
