### ISSUE TITLE
Add 'Tech Support' issue button to public login page

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#16]
Can we add a link to either the usahcourses@usahockey.org address or 'Submit a help ticket' to the public facing login page? Trying to give people a direction if the password reset, etc. isn't working.

**Comment by cameroneickmeyer** [comment]
Cam to provide link to public page

**Comment by cameroneickmeyer** [comment]
Help page link: http://www.usahockey.com/page/show/3441632-usa-hockey-coaches-and-officiating-course-registration-faq Can be labeled "Help & Tech Support"

**Comment by sn-np** [comment]
Added link to public sign on page.
