### ISSUE TITLE
Password reset strength check

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#17]
Process: User forgets password, clicks to reset, follows emailed token/link and resets, however doesn't enter a strong enough password. System accepts new password, but user is unable to sign in at next check.

Fix: He guessed the problem and the next time made his password complex and was then able to get in. Details: PC, Windows, Chrome

**Comment by sn-np** [comment]
The password reset page was checking the strength of the password, but not actually preventing you from using it (it did alert the user it was a bad password, but then went ahead and let them use it anyways). I've now prevented the bad password from being used in the first place.
