### ISSUE TITLE
User reports double charge

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#19]
We've had two instances of a user reporting a double charge for a clinic. We're checking into whether funds were actually pulled from the bank or just posted twice. The latest one is in the screenshot below. On our end we see one charge. Will update when we know more but wanted you to be aware ASAP.

![screen shot 2017-07-18 at 1 53 52 pm](https://user-images.githubusercontent.com/27363244/28337464-f052bca2-6bc2-11e7-8ef0-54788149b0a8.png)

**Comment by sn-np** [comment]
Ok. Keep me posted.  I checked the transaction logs and there is only one transaction being created (in this example, the transactions just before and just after are for other users). There don't appear to be any errors around those times either.

**Comment by cameroneickmeyer** [comment]
Update: The charges were separate but the user claims they were sent two confirmation emails as well. Do we have record of those messages? In all likelihood they saw separate confirmation emails for separate charges however I'd like to close the loop in the case we can confirm only one email went to them from Courses.

**Comment by sn-np** [comment]
We don't record e-mails that were sent.  But yes, if they have two separate charges they would receive another e-mail each time they are charged.

**Comment by cameroneickmeyer** [comment]
Closing as this does not appear to be a bug.
