### ISSUE TITLE
Text for "My Profile Page"

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#28]
![screen shot 2017-07-20 at 1 20 50 pm](https://user-images.githubusercontent.com/27363244/28434892-502691ee-6d4e-11e7-85be-d73738254cf8.png)

**Comment by cameroneickmeyer** [comment]
The green button is good, but some text like the screenshot above would really help cut down on questions.

**Comment by sn-np** [comment]
I just added more text to each of the profile pages indicating how they can update. I also extended the error message for not being able to register based on credentials to tell them to go refresh their profile.

You'll need to clear cache to see these changes.
