### ISSUE TITLE
Email Attendees should CC Instructor(s)

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#33]
When an email is sent to attendees of a course an email should also be sent to the Instructors assigned to the course. This is to let the instructor know the email was sent, spot any errors, etc.

**Comment by sn-np** [comment]
System now sends a copy of the message to any instructors on the course for both e-mailing an individual or all attendees.

**Comment by cameroneickmeyer** [comment]
Cleared cache and attempted to email Alison Raines from the CO Colorado Springs CEP High Performance course. Email window opens, typed message then hit send. Wheel flashes for a second then disappears without sending the email.

**Comment by sn-np** [comment]
Sorry bout that... I had tested with a walkup and not a registration. Should be good now.
