### ISSUE TITLE
Report type missing

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#35]
We need the ability to produce the attached report for System Admins only. 
[Copy of rr.xlsx](https://github.com/cameroneickmeyer/CoursesSystem/files/1174592/Copy.of.rr.xlsx)

**Comment by sn-np** [comment]
Several questions here:
1. I don't track an association or district for a registration. Are those key fields or can they be left blank?
2. What do start date and end date refer to? First and last session dates?
3. City and state refer to the registrant's info or the course info?
4. Clinic, lunch, total fee I assume are coming from the course specification. Should other fee be added here?
4b. If the course specification of the fees changes at some time, is it ok for the report to list the fees are they are currently? Or do we need to track what the fees were at the time of registration?
5. We aren't using verisign for anything.  Should that be a paypal number?
6. What does "Dropped" mean? Possibilities: the registration was cancelled, the student did not attend, or something else?
7. Is this for all courses or some subset?
8. Is this report being automatically read by one of Ralph's systems? If so, I'll need to know required fields, formatting specification, etc.

**Comment by sn-np** [comment]
Done.
