### ISSUE TITLE
Game Reporting Link Missing

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#37]
We need a link to Game Report System added to officials profile pages ASAP. Should live on "Officials Information" page and link to the system Neural Planet already manages.

**Comment by sn-np** [comment]
Isn't this already present on the officials page? The link for "Submit an incident report" is the second link on the officiating information page.

**Comment by cameroneickmeyer** [comment]
I misunderstood the bug report on my end. It was my page to fix not yours!
