### ISSUE TITLE
Wrong level displayed for official

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#38]
We've had a couple of these now where a user is one level and their profile shows them one level higher. We think it might be displaying "eligible level" instead of their current level?

Login: tanlaagoura@yahoo.com
NP User ID: 4536
Tool: Courses.usahockey.com
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Remote IP: 172.13.235.180
DateTime: 2017-07-26 19:47:40

First Name: Greg
Last Name: Tukalski
Email: Tanlaagoura@yahoo.com
Phone: 8054275592

Operating System: ios
Browser: chrome

Issue type: Officiating
Description: I just registered on the new system. It says I'm a level 2. However I'm not. I'm a level 1. Just letting you know so it can be fixed. Thanks, Greg tukalski Ref # 659062

**Comment by sn-np** [comment]
In this case (as in the others like it that I've seen), the referee in question does not have a current registration (i.e. they do not have a 1718 membership).  When they look at their profile, it explicitly says for Registration Level "No registration found".  

But it is accurate that the field from Ralph that I am displaying under Current Level is the "RefEligibleLvl". If you want me to jsut relabel "Current level" as "Eligible level" I can do that.

**Comment by cameroneickmeyer** [comment]
So as soon as this person registers for the year it will be fixed, correct? I think we might be able to punt to v2 if so. I think suppressing the data if not currently registered might be an option.

**Comment by cameroneickmeyer** [comment]
More context on this: Is it possible to suppress the display of "Current Level" until the card and crest are sent? That's technically when Current Level is determined/triggered. If that's the case that is our best solution.

**Comment by cameroneickmeyer** [comment]
Here's an idea, but want to gauge what impact it might have: Ralph can change the feed to not send eligible level, which would fix this field problem, but would that affect the system in other areas?

**Comment by sn-np** [comment]
I think the trick here is just determining what information you want displayed, with which labels. I thought "Current level" was supposed to be an indication of the maximum level they COULD register for. Based on the feedback, it seems this should be labeled "eligibility level"?

Here are the levels sent by Ralph and my label for them:
"Ref_EligibleLevel" => Current level
"Ref_RegLevel" => Registration level or "No registration found"

**Comment by cameroneickmeyer** [comment]
Let's change that to "Current Eligible Level" and that should fix it.

**Comment by sn-np** [comment]
This is done with addition of Current Level after card is sent. We don't show the eligible level at all.
