### ISSUE TITLE
Links should open new windows

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#39]
Login: ntxsuper@att.net
NP User ID: 509
Tool: Courses.usahockey.com
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Remote IP: 192.31.106.36
DateTime: 2017-07-26 20:44:56

First Name: Robert
Last Name: Williams
Email: ntxsuper@att.net
Phone: 817-988-4810

Operating System: win-10
Browser: chrome

Issue type: System
Description: When selecting a link in the description portion of an officiating seminar (in any browser: Chrome, Edge & Explorer), instead of opening up a new tab it goes to the new page in the current tab. Then in order to get back to the seminar you were looking at you have to log back in and then find the seminar you were looking at. It would be nice if the new page were to create a new tab and open up in the new tab and leave the current tab with the seminar information.

**Comment by sn-np** [comment]
A few things:

- The links mentioned here are being created by the administrator (not something I control)
- How links are opened is usually a browser configuration (well, to an extent...  the link can do some of the work, but then you have to be careful to avoid a phishing attack).

The easiest approach is just to right-click the link and choose "open in new tab"

**Comment by cameroneickmeyer** [comment]
OK, I see what you mean. We need to ask our instructors to designate those URLs to open in a new tab. I will relay this info.

**Comment by cameroneickmeyer** [comment]
Can you add under "Admin Tips" on the home screen:

When adding a link to a course details section, please click on the "Target" tab and set your link to "open in a new tab" to allow our users to stay in the courses system while still seeing your links
