### ISSUE TITLE
Odd error message when filtering courses

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#4]
I have seen this error a few times the last couple days when trying to filter the list of courses using any of the controls we have at the top of the page.
![screen shot 2017-07-11 at 8 11 52 am](https://user-images.githubusercontent.com/27363244/28072587-c5709e1c-6610-11e7-99b2-35fe67579306.png)

**Comment by sn-np** [comment]
Cameron: Have you only seen this on the courses page? Or has it come up in other contexts (users or locations for example?)

**Comment by cameroneickmeyer** [comment]
Only seen it on the courses page filtering.

**Comment by sn-np** [comment]
I've put in a "fix" for this -- its in quotes because I'm not positive I've addressed the root cause (unknown?) but I think I've found a way to circumvent it. Please let me know if you see it again (after refresh).
