### ISSUE TITLE
Cosmetic changes to Officiating Information Page

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#40]
Some bugs spotted on the officiating information page:

- Red "X" for incomplete not showing up for fields Online Seminar, Classroom Seminar, Seminar Location, Card Sent

- Sorting of 10-year history should be new to old

- Move field for "Current Level" beneath "Card Sent"

**Comment by sn-np** [comment]
I added the red x for online seminar and classroom seminar, but I don't think it makes sense for a location (cause the seminar dates will already have the symbols) or card sent (will have a date once its through -- nothing they can do about it in the meantime, right?).

**Comment by cameroneickmeyer** [comment]
Correct

Sent from my iPhone

On Jul 31, 2017, at 5:40 PM, sn-np <notifications@github.com<mailto:notifications@github.com>> wrote:


I added the red x for online seminar and classroom seminar, but I don't think it makes sense for a location (cause the seminar dates will already have the symbols) or card sent (will have a date once its through -- nothing they can do about it in the meantime, right?).

**Comment by cameroneickmeyer** [comment]
One field I failed to mention that we want to appear and have "Missing" labels until 'Passed' is in there is Officiating Exam Information. Also for Level 4 officials the skate exam should be there with the same label. We want them to visually see what's missing so that they know why their overall certification is not yet done.

**Comment by sn-np** [comment]
Done.
