### ISSUE TITLE
Chrome bug: Map overlay on text

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#44]
When in chrome go to http://www.usahockey.com/coachingclinics then search for NY Level 4 CEP courses. Click on the Williamsville course and the map covers the course details.
![screen shot 2017-08-02 at 3 49 26 pm](https://user-images.githubusercontent.com/27363244/28896608-61b334de-779a-11e7-8c7d-93a0cdec5b92.png)

**Comment by sn-np** [comment]
Fixed.
