### ISSUE TITLE
Deleting Walkup

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#47]
There isn't a mechanism for deleting a walkup if an admin inadvertently put them in there. For example adds someone as a walkup who was already registered, or typos some information.

Open to ideas.

**Comment by sn-np** [comment]
Right. I asked about this early on and was told that walkups would never need to be deleted cause if they were a walkup, obviously they were there.

That said, we can probably add the button... but I'd probably want to put a sys admin access permission on it or something. Or do you want anyone to be able to delete them?

**Comment by cameroneickmeyer** [comment]
Correct that we said we wouldn't have to delete but right out of the gate we have an admin who says in the past he's made typos and then had to change names to "not real person" etc. 

We want the local person to be able to fix their own mistakes but maybe if you "delete" you don't really remove and just gray them out instead? Very open to suggestions.
