### ISSUE TITLE
v1.x: Multi-Level Seminar Attendee display

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#54]
Problem: Multi-Level Seminars do NOT display the level each attendee is trying to take. This is a known issue and decision made by USAH to not display/sort. This has become cumbersome for instructors of these seminars who want to see who is coming for which level.

Solution: Display on the attendee page the level applied for and make the column sortable. Or we could group them into their levels as well. Open to suggestions.

**Comment by sn-np** [comment]
Added a Level column to both the registrations and walkups table.
