### ISSUE TITLE
Time problem

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#7]
This course (Kent OH Kent Ref Level 3) has an end time of 12:00 PM but on the public display it's showing 12:00 AM

![screen shot 2017-07-11 at 10 32 49 am](https://user-images.githubusercontent.com/27363244/28079116-5ce412de-6624-11e7-992f-333565d7b98b.png)

![screen shot 2017-07-11 at 10 34 58 am](https://user-images.githubusercontent.com/27363244/28079198-a03325e8-6624-11e7-89fa-173adf7a455e.png)

**Comment by sn-np** [comment]
This is fixed. Will need to refresh.
