### ISSUE TITLE
Season label

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#85]
Change text "2017-18" to read "2018-19" on login screens, membership update screen, profile creation, etc

**Comment by sn-np** [comment]
The only place we have anything specific to a season is when a user is attempting to login from the external interface where we say: 
"Welcome to the new course registration system for the 2017-18 season. If you have not already used this new system you will need to first create an account."

I've reworded it like this:
"Welcome to the course registration system that was new for the 2017-18 season. If you have not already used this system you will need to first create an account."

In all other places where we used to say "17-18" it is now the case that we don't mention season at all. For example, when you are creating an account, we say "Please enter your USA Hockey confirmation number"

**Comment by sn-np** [comment]
Removed.
