### ISSUE TITLE
Can't register for coaching clinic

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#86]
using cameickmeyer@gmail.com and register for PA Allentown CEP 1 course. Says don't meet requirements but I think I do?

**Comment by sn-np** [comment]
Not quite sure what to make of this one.  There is a 17-18 coaching membership (level 0) associated with the email indicated. That should be ok to register for 3 of the 4 PA Allentown CEP 1 courses (the one on 12/1/2018 requires an 18-19 number). That said, somehow the coaching membership associated with that e-mail hasn't been refreshed, even though an officiating membership was added on 5/11. I'm not sure how you could have added the new membership without first logging in, which should have caused a profile refresh. Based on the logs, it doesn't look like there was any sort of merge involved (which could have been one way to get in this state), so I'm a bit flummoxed.

Let's start here: please try to log in and register again (making sure to use a course before 9/1/2018) and let's see if we can recreate any portion of this behavior.

**Comment by cameroneickmeyer** [comment]
The one step I tried was merge but stopped before completing. Could that have done it?

**Comment by sn-np** [comment]
I think I (finally) figured some pieces of this out. The first key discovery is the fact that the coaching membership you have on record for cameickmeyer@gmail.com is not a valid confirmation number (119860008EICK - needs to have 9 numbers followed by 5 letters).  This account was created back before we had a confirmation number format check in place (though I'm still curious if the member lookup actually gave information for that number??). Anyways, this is how you were able to log in as that user, but not have the membership update (puzzle #1 solved!). 

So then you tried to register for course 1779, which I agree, should go through even with the old information from your record. Would you please log in again and tell me the exact wording of the error message generated?

**Comment by cameroneickmeyer** [comment]
![screen shot 2018-05-15 at 3 33 42 pm](https://user-images.githubusercontent.com/27363244/40084757-6dc35c12-5855-11e8-9e09-77a357e43380.png)

**Comment by sn-np** [comment]
I think I found this one. Please verify.

**Comment by cameroneickmeyer** [comment]
Was able to reach payment screen, but am now stuck and unable to reach confirmation screen

**Comment by sn-np** [comment]
Silly mistake. Sorry! Try one more time.
