### ISSUE TITLE
Member number not linking

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#9]
This user has a valid profile and valid member numbers for 16-17 & 17-18, however the current number doesn't show on his profile and trying to add the number gives an error that the number is already in use. Searching for 186800747BLOCK in lookup gives me his name but doesn't show that number only 16-17. Screenshot attached.
![screen shot 2017-07-12 at 1 58 53 pm](https://user-images.githubusercontent.com/27363244/28137422-799040e2-670a-11e7-878d-27a4d2d908bb.png)

**Comment by sn-np** [comment]
This user's coaching membership information looks decidedly strange:
120750506BLOCK is associated with 16/17 and a certification level of 0.
264702666XXBL is also associated with 16/17 but now has a certification level of 3
186800747BLOCK is associated with 17/18 and is back to a certification level of 0.

Which of these should actually be in the system?

**Comment by cameroneickmeyer** [comment]
The only thing that could be causing this problem is the "XXBL" number which represents an unpaid volunteer number and shouldn't factor in or if possible be rejected. Those types of accounts always have "XX" as the first two letters of that portion of a number. 

- He should be a Level 3 coach so can we see what happens if we remove that number?
- Is removing a number an option for a coach?
- Is it possible to reject those numbers?

**Comment by sn-np** [comment]
- I can remove the XXBLO number (and did so), but his 17/18 season info is still showing him as level 0.  Sounds like he'll need to do a refresh before he can register if his info has been corrected on the USAH side of things

- To remove a number is possible programatically, but not currently implemented. Maybe we put this on a 1.x or 2.0 feature list?

- To reject those numbers, I would need to know the specific format to disallow. Is it XX always followed by 3 letters? Or is it really that the first number (in this case 2) is what says it is a volunteer number and shouldn't be used for determining course eligibility?

**Comment by cameroneickmeyer** [comment]
Please remove his XXBLO number and I'll have him do the profile reset. I'll make a new issue to offer "remove a number" for version2. Format for these volunteer numbers is:

Nine numbers, XX,  then first three letters of the last name. It's also classified as member type H if that helps at all.

**Comment by cameroneickmeyer** [comment]
Is the rejection of these types of numbers in process? Or just conceptual right now?

**Comment by sn-np** [comment]
I pushed a change that does these validation checks:
Conf number is 9 digits followed by 5 letters, the first two of the letters may not be XX
Officials id must be at least 1 digit, and only digits
