### ISSUE TITLE
Icons needed on mobile in 2.0

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#94]
Locations, User lookup, Admin and Archive are all spelled out in mobile view while signed in as admin. Can we get icons for those?

Maybe a map pin, a magnifying glass, key and a folder?

**Comment by sn-np** [comment]
I just pushed some icons out. I went ahead and put them both on staging and live since I was pretty sure the ones Dominic came up with would work. Let me know what you think.

**Comment by cameroneickmeyer** [comment]
Perfect
