### ISSUE TITLE
Incorrect password message change

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#95]
When you put in a wrong password the 2017-18 terminology is still there. Can we swap that for "current season" like the other messages?

**Comment by sn-np** [comment]
The wording there says:
Are you sure you have an account?
This system is new for the 2017-18 season.  Try creating an account.

Do you want to remove the line about the system being new? Or update to say "This system **was** new for the 2017-18 season" Or something else?

**Comment by cameroneickmeyer** [comment]
ah, my mistake. Yes, "was" will suffice. Then next year we can just end with "Are you sure you have an account?"

**Comment by sn-np** [comment]
Fixed.
